{% set name = "tonic" %}
{% set version = "0.3.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tonic-{{ version }}.tar.gz
  sha256: a14e8c64221026e2f8e7ebc2093dca4a6a04bde65bf67509362c9d3a5f4994f8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - loris
    - numpy
    - python >=3.6
    - tqdm
    - matplotlib-base
    - scipy
    - torchvision
    - h5py
    - importrosbag

test:
  imports:
    - tonic
    - tonic.datasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neuromorphs/tonic
  summary: Event-based datasets and transformations based on pyTorch vision.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
