{% set name = "tonic" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tonic-{{ version }}.tar.gz
  sha256: 8ca5e97e30a9180ba77b39b8124cdad596660530da47ca3b01800f0e975628a4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - loris
    - numpy
    - python >=3.6
    - tqdm
    - matplotlib-base
    - scipy
    - torchvision
    - h5py

test:
  imports:
    - tonic
    - tonic.datasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neuromorphs/tonic
  summary: Event-based datasets and transformations based on pyTorch vision.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
